### PR TITLE
Cord perm

### PR DESCRIPTION
**Pull request by staniboy**
Hello, could something like this be implemented?

### CODE REVIEW

**Comment by Jarada** [comment]
Hi there,

Apologies for the slow reply. This should be doable, I should have this done and released by the end of this week, once I get around to testing the change.

If you'd like a preview release prior to this, feel free to open a support ticket on the Discord.

**Review by Twitter1268 — APPROVED** [review]

**Comment by Jarada** [comment]
New permission is `wg.view.coords`

**Review by Twitter1268 — COMMENTED** [review]
@Twitter1268

**Review by Twitter1268 — COMMENTED** [review]
d70fcff

**Pull request closed without merging**
